name: Trigger Jenkins
on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1.15.5
      with:
        url: "${{ secrets.JENKINS_URL }}"
        method: 'POST'
        customHeaders: '{"token": "${{ secrets.JENKINS_TOKEN }}"}'
